name: commitlint
on:
  pull_request:
jobs:
  commitlint:
    permissions:
      contents: read
    uses: unabandoned/.github/.github/workflows/reusable-commitlint.yml@ae2bd5a86503774166346992cf1a5eeef28117bc # main
