name: release-security
on:
  pull_request:
    types: [closed]
jobs:
  security-release:
    permissions:
      contents: write
      pull-requests: write
    uses: unabandoned/.github/.github/workflows/reusable-release-security.yml@ae2bd5a86503774166346992cf1a5eeef28117bc # main
    secrets: inherit
