name: release-cut
on:
  schedule:
    - cron: '0 6 1 * *'
  workflow_dispatch:
jobs:
  cut:
    permissions:
      contents: write
      pull-requests: write
    uses: unabandoned/.github/.github/workflows/reusable-release-cut.yml@ae2bd5a86503774166346992cf1a5eeef28117bc # main
    secrets: inherit
