name: Scorecard
on:
  branch_protection_rule:
  schedule:
    - cron: '0 6 * * 1'
  push:
    branches: [main]
jobs:
  scorecard:
    permissions:
      security-events: write
      id-token: write
      contents: read
    uses: unabandoned/.github/.github/workflows/reusable-scorecard.yml@ae2bd5a86503774166346992cf1a5eeef28117bc # main
